#!/bin/bash

# kmodtool - Helper script for building kernel module RPMs
# Copyright (c) 2003-2014 Ville Skyttä <ville.skytta@iki.fi>,
#                         Thorsten Leemhuis <fedora@leemhuis.info>
#                         Nicolas Chauvet <kwizart@gmail.com>
#                         Aleksey Avdeev <avdeev@altell.ru>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

shopt -s extglob

myprog="kmodtool-${repo}"
myver="0.12.1"

kmodgroups=
kmodname=
build_kernels="current"
kernels_known_variants=
kernel_versions=
kernel_versions_to_build_for=
prefix=
filterfile=
target=

error_out()
{
	local errorlevel=${1}
	shift
	echo "Error: $@" >&2
	# the next line is not multi-line safe -- not needed *yet*
	echo "%global kmodtool_check echo \"kmodtool error: $@\"; exit ${errorlevel};"
	exit ${errorlevel}
}

print_rpmtemplate_header()
{
	echo
	echo '%global kmodinstdir_prefix  '/usr/lib/modules
	echo '%global kmodinstdir_postfix '/extra/${kmodname}
	echo '%global kernel_versions     '${kernel_versions}

	if [[ "${kmodgroups}" ]]; then
		echo '%global kmodgroups_list     '%{?akmodgroup}%{!?akmodgroup:${kmodgroups}}
	fi

	echo
}

print_akmodtemplate ()
{
	local group

	echo
	echo -n '%global akmod_install mkdir -p $RPM_BUILD_ROOT/%{_usrsrc}/akmods/; '

	if [[ ! "${kmodgroups}" ]]; then
		echo -n 'rpmbuild --define "_sourcedir %{_sourcedir}" '
		echo -n '--define "_srcrpmdir $RPM_BUILD_ROOT/%{_usrsrc}/akmods/" '
		echo -n '-bs --nodeps %{_specdir}/%{name}.spec ; '
		echo -n "ln -s \$(ls \$RPM_BUILD_ROOT/%{_usrsrc}/akmods/) \$RPM_BUILD_ROOT/%{_usrsrc}/akmods/${kmodname}-kmod.latest"
		echo
	else
		for group in ${kmodgroups}
		do
			echo -n "echo %%%%global akmodgroup ${group} > %{name}-${group}.spec; "
			echo -n "cat %{_specdir}/%{name}.spec >> %{name}-${group}.spec ; "
			echo -n 'rpmbuild --define "_sourcedir %{_sourcedir}" '
			echo -n '--define "_srcrpmdir $RPM_BUILD_ROOT/%{_usrsrc}/akmods/" '
			echo -n "-bs --nodeps %{name}-${group}.spec ; "
			echo -n "mv \$RPM_BUILD_ROOT/%{_usrsrc}/akmods/%{name}-%{version}-%{release}.src.rpm \$RPM_BUILD_ROOT/%{_usrsrc}/akmods/%{name}-${group}-%{version}-%{release}.src.rpm ; "
			echo -n "ln -s %{name}-${group}-%{version}-%{release}.src.rpm \$RPM_BUILD_ROOT/%{_usrsrc}/akmods/${kmodname}-${group}-kmod.latest; "
		done

		echo
	fi

	cat <<EOF

%package -n akmod-${kmodname}
EOF

	if [[ ! "${kmodgroups}" ]]; then
		cat <<EOF
Summary:	Akmod package for ${kmodname} kernel module(s) 
EOF

	else
		cat <<EOF
Summary:	Metapackage which tracks akmod packages for ${kmodname} kernel module(s) 
EOF

	fi

	cat <<EOF
Group: 		System Environment/Kernel
EOF

	if [[ ! "${kmodgroups}" ]]; then
		cat <<EOF
Requires:   kmodtool
Requires: 	akmods
%{?AkmodsBuildRequires:Requires: %{AkmodsBuildRequires}}
# same requires and provides as a kmods package would have
Requires: 	${kmodname}-kmod-common >= %{?epoch:%{epoch}:}%{version}
EOF

	else
		for group in ${kmodgroups}
		do
			cat <<EOF
Requires: 	akmod-${kmodname}-${group} = %{?epoch:%{epoch}:}%{version}-%{release}
EOF

		done
	fi

	cat <<EOF
Provides: 	${kmodname}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
EOF

	if [[ ${obsolete_name} ]]; then
		echo "Provides:   akmod-${obsolete_name} = ${obsolete_version}"
		echo "Obsoletes:  akmod-${obsolete_name} < ${obsolete_version}"
	fi

	cat <<EOF

%description -n akmod-${kmodname}
EOF

	if [[ ! "${kmodgroups}" ]]; then
		cat <<EOF
This package provides the akmod package for the ${kmodname} kernel modules.

%posttrans -n akmod-${kmodname}
nohup /usr/sbin/akmods --from-akmod-posttrans --akmod ${kmodname} &> /dev/null &

EOF

	else
		cat <<EOF
This is a meta-package without payload which sole purpose is to require the
akmod packages for the ${kmodname} kernel modules.

EOF

	fi

	cat <<EOF

%files -n akmod-${kmodname}
EOF

	if [[ ! "${kmodgroups}" ]]; then
		cat <<EOF
%defattr(-,root,root,-)
%{_usrsrc}/akmods/*

EOF

	else
		echo

		for group in ${kmodgroups}
		do
			cat <<EOF
%package -n akmod-${kmodname}-${group}
Summary:	Akmod package for ${kmodname}-${group} kernel module(s) 
Group: 		System Environment/Kernel
Requires:   kmodtool
Requires: 	akmods
%{?AkmodsBuildRequires:Requires: %{AkmodsBuildRequires}}
# same requires and provides as a kmods package would have
Requires: 	${kmodname}-kmod-common >= %{?epoch:%{epoch}:}%{version}
Provides: 	${kmodname}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Provides: 	${kmodname}-${group}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
EOF

		if [[ ${obsolete_name} ]]; then
			echo "Provides:   akmod-${obsolete_name}-${group} = ${obsolete_version}"
			echo "Obsoletes:  akmod-${obsolete_name}-${group} < ${obsolete_version}"
		fi

			cat <<EOF
Conflicts: 	akmod-${kmodname} < %{?epoch:%{epoch}:}%{version}-%{release}

%description -n akmod-${kmodname}-${group}
This package provides the akmod package for the ${kmodname}-${group} kernel modules.

%posttrans -n akmod-${kmodname}-${group}
nohup /usr/sbin/akmods --from-akmod-posttrans --akmod ${kmodname}-${group} &> /dev/null &


%files -n akmod-${kmodname}-${group}

%defattr(-,root,root,-)
%{_usrsrc}/akmods/%{name}-${group}-%{version}-%{release}.src.rpm
%{_usrsrc}/akmods/${kmodname}-${group}-kmod.latest

EOF

		done
	fi
}

print_akmodmeta ()
{
	local group

		cat <<EOF
%package      -n kmod-${kmodname}
Summary:         Metapackage which tracks in ${kmodname} kernel module for newest kernel${dashvariant}
Group:           System Environment/Kernel

Provides:        ${kmodname}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-xen = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-smp = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-PAE = %{?epoch:%{epoch}:}%{version}-%{release}
Requires:        akmod-${kmodname} = %{?epoch:%{epoch}:}%{version}-%{release}
EOF

	if [[ "${kmodgroups}" ]]; then
		for group in ${kmodgroups}
		do
			cat <<EOF
Requires:        kmod-${kmodname}-${group} = %{?epoch:%{epoch}:}%{version}-%{release}
EOF

		done
	fi

	if [[ ${obsolete_name} ]]; then
		echo "Provides:        kmod-${obsolete_name} = ${obsolete_version}"
		echo "Obsoletes:       kmod-${obsolete_name} < ${obsolete_version}"
	fi

cat <<EOF

%description  -n kmod-${kmodname}${dashvariant}
This is a meta-package without payload which sole purpose is to require the
${kmodname} kernel module(s) for the newest kernel${dashvariant},
to make sure you get it together with a new kernel.

%files        -n kmod-${kmodname}${dashvariant}
%defattr(644,root,root,755)
EOF

	if [[ "${kmodgroups}" ]]; then
		echo

		for group in ${kmodgroups}
		do
			cat <<EOF
%package      -n kmod-${kmodname}-${group}
Summary:         Metapackage which tracks in ${kmodname}-${group} kernel module for newest kernel${dashvariant}
Group:           System Environment/Kernel

Provides:        ${kmodname}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        ${kmodname}-${group}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-xen = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-${group}-xen = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-smp = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-${group}-smp = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-PAE = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        kmod-${kmodname}-${group}-PAE = %{?epoch:%{epoch}:}%{version}-%{release}
Requires:        akmod-${kmodname}-${group} = %{?epoch:%{epoch}:}%{version}-%{release}
EOF

			if [[ ${obsolete_name} ]]; then
				echo "Provides:        kmod-${obsolete_name}-${group} = ${obsolete_version}"
				echo "Obsoletes:       kmod-${obsolete_name}-${group} < ${obsolete_version}"
			fi

			cat <<EOF
Conflicts: 	kmod-${kmodname} < %{?epoch:%{epoch}:}%{version}-%{release}

%description  -n kmod-${kmodname}-${group}
This is a meta-package without payload which sole purpose is to require the
${kmodname}-${group} kernel module(s) for the newest kernel,
to make sure you get it together with a new kernel.

%files        -n kmod-${kmodname}-${group}
%defattr(644,root,root,755)
EOF
		done
	fi
}

print_rpmtemplate_per_kmodpkg ()
{
	local group

	if [[ "${1}" == "--custom" ]]; then
		shift
		local customkernel=true
	elif [[ "${1}" == "--redhat" ]]; then
		# this is needed for akmods
		shift
		local redhatkernel=true
	fi

	local kernel_uname_r=${1}
	local kernel_variant="${2:+-${2}}"

    # first part
	if [[ "${kmodgroups}" ]]; then
		cat <<EOF
%if "%{?akmodgroup}" == ""
EOF

	fi

	cat <<EOF
%package       -n kmod-${kmodname}-${kernel_uname_r}
EOF

	if [[ ! "${kmodgroups}" ]]; then
		cat <<EOF
Summary:          ${kmodname} kernel module(s) for ${kernel_uname_r}
EOF

	else
		cat <<EOF
Summary:          Metapackage which tracks in ${kmodname} kernel module(s) for ${kernel_uname_r}
EOF

	fi

	cat <<EOF
Group:            System Environment/Kernel
Provides:         kernel-modules-for-kernel = ${kernel_uname_r}
Provides:         ${kmodname}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
EOF

	if [[ ! "${kmodgroups}" ]]; then
		cat <<EOF
Requires:         ${kmodname}-kmod-common >= %{?epoch:%{epoch}:}%{version}
Requires(post):   /usr/sbin/depmod
Requires(postun): /usr/sbin/depmod
EOF

	else
		for group in ${kmodgroups}
		do
			cat <<EOF
Requires: 	kmod-${kmodname}-${group}-${kernel_uname_r} = %{?epoch:%{epoch}:}%{version}
EOF

		done
	fi

	if [[ ${obsolete_name} ]]; then
		echo "Provides:        kmod-${obsolete_name}-${kernel_uname_r} = ${obsolete_version}"
		echo "Obsoletes:       kmod-${obsolete_name}-${kernel_uname_r} < ${obsolete_version}"
	fi

	# second part
	if [[ ! "${kmodgroups}" ]]; then
		if [[ ! "${customkernel}" ]]; then
		     cat <<EOF
Requires:         kernel-uname-r = ${kernel_uname_r}
BuildRequires:	  kernel-devel-uname-r = ${kernel_uname_r}
%post          -n kmod-${kmodname}-${kernel_uname_r}
/usr/sbin/depmod -aeF /boot/System.map-${kernel_uname_r} ${kernel_uname_r} > /dev/null || :
%postun        -n kmod-${kmodname}-${kernel_uname_r}
/usr/sbin/depmod  -aF /boot/System.map-${kernel_uname_r} ${kernel_uname_r} &> /dev/null || :

EOF
		else
		  cat <<EOF
%post          -n kmod-${kmodname}-${kernel_uname_r}
[[ "$(uname -r)" == "${kernel_uname_r}"  ]] && /usr/sbin/depmod -a > /dev/null || :
%postun        -n kmod-${kmodname}-${kernel_uname_r}
[[ "$(uname -r)" == "${kernel_uname_r}"  ]] && /usr/sbin/depmod -a > /dev/null || :

EOF
		fi
	fi

  # third part
	cat <<EOF
%description  -n kmod-${kmodname}-${kernel_uname_r}
EOF

	if [[ ! "${kmodgroups}" ]]; then
		cat <<EOF
This package provides the ${kmodname} kernel modules built for the Linux
kernel ${kernel_uname_r} for the %{_target_cpu} family of processors.
EOF

	else
		for group in ${kmodgroups}
		do
			cat <<EOF
This is a meta-package without payload which sole purpose is to require the
kmod packages for the ${kmodname} kernel ${kernel_uname_r} modules.
EOF

		done
	fi

	cat <<EOF

%files        -n kmod-${kmodname}-${kernel_uname_r}
%defattr(644,root,root,755)
EOF

	if [[ ! "${kmodgroups}" ]]; then
		cat <<EOF
%dir /usr/lib/modules/${kernel_uname_r}/extra
/usr/lib/modules/${kernel_uname_r}/extra/${kmodname}/


EOF

	else
		cat <<EOF
%endif


EOF

		for group in ${kmodgroups}
		do
			cat <<EOF
%package       -n kmod-${kmodname}-${group}-${kernel_uname_r}
Summary:          ${kmodname}-${group} kernel module(s) for ${kernel_uname_r}
Group:            System Environment/Kernel
Provides:         kernel-modules-for-kernel = ${kernel_uname_r}
Provides:         ${kmodname}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:         ${kmodname}-${group}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Requires:         ${kmodname}-kmod-common >= %{?epoch:%{epoch}:}%{version}
Requires(post):   /usr/sbin/depmod
Requires(postun): /usr/sbin/depmod
Provides:        kmod-${kmodname}-${kernel_uname_r} = %{?epoch:%{epoch}:}%{version}-%{release}
Obsoletes:       kmod-${kmodname}-${kernel_uname_r} < %{?epoch:%{epoch}:}%{version}-%{release}
EOF

			if [[ ${obsolete_name} ]]; then
				echo "Provides:        kmod-${obsolete_name}-${kernel_uname_r} = ${obsolete_version}"
				echo "Obsoletes:       kmod-${obsolete_name}-${kernel_uname_r} < ${obsolete_version}"
				echo "Provides:        kmod-${obsolete_name}-${group}-${kernel_uname_r} = ${obsolete_version}"
				echo "Obsoletes:       kmod-${obsolete_name}-${group}-${kernel_uname_r} < ${obsolete_version}"
			fi

			# second part
			if [[ ! "${customkernel}" ]]; then
				cat <<EOF
Requires:         kernel-uname-r = ${kernel_uname_r}
BuildRequires:	  kernel-devel-uname-r = ${kernel_uname_r}
%post          -n kmod-${kmodname}-${group}-${kernel_uname_r}
/usr/sbin/depmod -aeF /boot/System.map-${kernel_uname_r} ${kernel_uname_r} > /dev/null || :
%postun        -n kmod-${kmodname}-${group}-${kernel_uname_r}
/usr/sbin/depmod  -aF /boot/System.map-${kernel_uname_r} ${kernel_uname_r} &> /dev/null || :

EOF
			else
			 	cat <<EOF
%post          -n kmod-${kmodname}-${group}-${kernel_uname_r}
[[ "$(uname -r)" == "${kernel_uname_r}"  ]] && /usr/sbin/depmod -a > /dev/null || :
%postun        -n kmod-${kmodname}-${group}-${kernel_uname_r}
[[ "$(uname -r)" == "${kernel_uname_r}"  ]] && /usr/sbin/depmod -a > /dev/null || :

EOF

			fi

			# third part
			cat <<EOF
%description  -n kmod-${kmodname}-${group}-${kernel_uname_r}
This package provides the ${kmodname}-${group} kernel modules built for the Linux
kernel ${kernel_uname_r} for the %{_target_cpu} family of processors.

%files        -n kmod-${kmodname}-${group}-${kernel_uname_r}
%defattr(644,root,root,755)
%dir /usr/lib/modules/${kernel_uname_r}/extra
/usr/lib/modules/${kernel_uname_r}/extra/${kmodname}-${group}/


EOF

		done
	fi
}

print_rpmtemplate_kmodmetapkg ()
{
		local group

		local kernel_uname_r=${1}
		local kernel_variant="${2:+-${2}}"

		cat <<EOF
%package      -n kmod-${kmodname}${kernel_variant}
Summary:         Metapackage which tracks in ${kmodname} kernel module for newest kernel${kernel_variant}
Group:           System Environment/Kernel

Provides:        ${kmodname}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
EOF

		if [[ ! "${kmodgroups}" ]]; then
			cat <<EOF
Requires:        kmod-${kmodname}-${kernel_uname_r} >= %{?epoch:%{epoch}:}%{version}-%{release}
EOF

		else
			for group in ${kmodgroups}
			do
				cat <<EOF
Requires:        kmod-${kmodname}-${group}${kernel_variant} >= %{?epoch:%{epoch}:}%{version}-%{release}
EOF

			done
		fi
	
		if [[ ${obsolete_name} ]]; then
			echo "Provides:        kmod-${obsolete_name}${kernel_variant} = ${obsolete_version}"
			echo "Obsoletes:       kmod-${obsolete_name}${kernel_variant} < ${obsolete_version}"
		fi

		cat <<EOF

%description  -n kmod-${kmodname}${kernel_variant}
This is a meta-package without payload which sole purpose is to require the
${kmodname} kernel module(s) for the newest kernel${kernel_variant}.
to make sure you get it together with a new kernel.

%files        -n kmod-${kmodname}${kernel_variant}
%defattr(644,root,root,755)


EOF

		if [[ ! "${kmodgroups}" ]]; then
			for group in ${kmodgroups}
			do
				cat <<EOF
%package      -n kmod-${kmodname}-${group}${kernel_variant}
Summary:         Metapackage which tracks in ${kmodname}-${group} kernel module for newest kernel${kernel_variant}
Group:           System Environment/Kernel

Provides:        ${kmodname}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:        ${kmodname}-${group}-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Requires:        kmod-${kmodname}-${group}-${kernel_uname_r} >= %{?epoch:%{epoch}:}%{version}-%{release}
EOF

			if [[ ${obsolete_name} ]]; then
				echo "Provides:        kmod-${obsolete_name}-${group}${kernel_variant} = ${obsolete_version}"
				echo "Obsoletes:       kmod-${obsolete_name}-${group}${kernel_variant} < ${obsolete_version}"
			fi

			cat <<EOF

%description  -n kmod-${kmodname}-${group}${kernel_variant}
This is a meta-package without payload which sole purpose is to require the
${kmodname}-${group} kernel module(s) for the newest kernel${kernel_variant}.
to make sure you get it together with a new kernel.

%files        -n kmod-${kmodname}-${group}${kernel_variant}
%defattr(644,root,root,755)


EOF
			done
		fi
}

print_customrpmtemplate ()
{
	for kernel in ${1}
	do
		if 	[[ -e "/usr/src/kernels/${kernel}" ]] ; then
			# this looks like a Fedora/RH kernel -- print a normal template (which includes the proper BR) and be happy :)
			kernel_versions="${kernel_versions}${kernel}___%{_usrsrc}/kernels/${kernel} "

			# parse kernel versions string and print template
			local kernel_verrelarch=${kernel%%${kernels_known_variants}}
			print_rpmtemplate_per_kmodpkg --redhat ${kernel} ${kernel##${kernel_verrelarch}}
		elif [[ -e /usr/lib/modules/"${kernel}"/build/Makefile ]] ; then 
			# likely a user-build-kernel with available buildfiles
			# fixme: we should check if uname from Makefile is the same as ${kernel}

			kernel_versions="${kernel_versions}${kernel}___/usr/lib/modules/${kernel}/build/ "
			print_rpmtemplate_per_kmodpkg --custom "${kernel}"
		else
			error_out 2 "Don't know how to handle ${kernel} -- /usr/lib/modules/${kernel}/build/Makefile not found"
		fi
	done

	# well, it's no header anymore, but who cares ;-)
	print_rpmtemplate_header
}


print_rpmtemplate ()
{
	# create kernel_versions var
	for kernel_version in ${kernel_versions_to_build_for}
	do
		kernel_versions="${kernel_versions}${kernel_version}___%{_usrsrc}/kernels/${kernel_version} "
	done

	# and print it and some other required stuff as macro
	print_rpmtemplate_header

	# now print the packages itselfs
	for kernel in ${kernel_versions_to_build_for} ; do

		local kernel_verrelarch=${kernel%%${kernels_known_variants}}

		# create metapackage 
		print_rpmtemplate_kmodmetapkg ${kernel} ${kernel##${kernel_verrelarch}}

		# create package
		print_rpmtemplate_per_kmodpkg ${kernel} ${kernel##${kernel_verrelarch}}
	done
}

myprog_help ()
{
	echo "Usage: $(basename ${0}) [OPTIONS]"
	echo $'\n'"Creates a template to be used during kmod building"
	echo $'\n'"Available options:"
	# FIXME	echo " --datadir <dir>     -- look for our shared files in <dir>"
	echo " --filterfile <file>  -- filter the results with grep --file <file>"
	echo " --for-kernels <list> -- created templates only for these kernels"
	echo " --kmodgroups <list>  -- names of the kmod groups"
	echo " --kmodname <file>    -- name of the kmod (required)"
	echo " --noakmod            -- no akmod package"
	echo " --repo <name>        -- use buildsys-build-<name>-kerneldevpkgs"
	echo " --target <arch>      -- target-arch (required)"
}

while [ "${1}" ] ; do
	case "${1}" in
		--filterfile)
			shift
			if [[ ! "${1}" ]] ; then
				error_out 2 "Please provide path to a filter-file together with --filterfile" >&2
			elif [[ ! -e "${1}" ]]; then	
				error_out 2 "Filterfile ${1} not found" >&2
			fi
			filterfile="${1}"
			shift
			;;
		--kmodname)
			shift
			if [[ ! "${1}" ]] ; then
				error_out 2 "Please provide the name of the kmod together with --kmodname" >&2
	 	    fi
			# strip pending -kmod
			kmodname="${1%%-kmod}"
			shift
			;;
		--kmodgroups)
			shift
			if [[ ! "${1}" ]] ; then
				error_out 2 "Please provide the list of the kmod groups together with --kmodgroups." >&2
			fi
			kmodgroups="${1}"
			shift
			;;
		--repo)
			shift
			if [[ ! "${1}" ]] ; then
				error_out 2 "Please provide the name of the repo together with --repo" >&2
	 	    fi
			repo=${1}
			shift
			;;
		--for-kernels)
			shift
			if [[ ! "${1}" ]] ; then
				error_out 2 "Please provide the name of the kmod together with --kmodname" >&2
	 		fi
			for_kernels="${1}"
			shift
			;;
		--noakmod)
			shift
			noakmod="true"
			;;
		--obsolete-name)
			shift
			if [[ ! "${1}" ]] ; then
				error_out 2 "Please provide the name of the kmod to obsolte together with --obsolete-name" >&2
	 		fi
			obsolete_name="${1}"
			shift
			;;
		--obsolete-version)
			shift
			if [[ ! "${1}" ]] ; then
				error_out 2 "Please provide the version of the kmod to obsolte together with --obsolete-version" >&2
	 		fi
			obsolete_version="${1}"
			shift
			;;
		--target)
			shift
			target="${1}"
			shift
			;;
		--akmod)
			shift
			build_kernels="akmod"
			;;
		--newest)
			shift
			build_kernels="newest"
			;;
		--current)
			shift
			build_kernels="current"
			;;
		--help)
			myprog_help
			exit 0
			;;
		--version)
			echo "${myprog} ${myver}"
			exit 0
			;;
		*)
			echo "Error: Unknown option '${1}'." >&2
			usage >&2
			exit 2
			;;
	esac
done

if [[ -e ./kmodtool-kernel-variants ]]; then
	kernels_known_variants="$(cat ./kmodtool-kernel-variants)"
elif [[ -e /usr/share/kmodtool/kernel-variants ]] ; then
	kernels_known_variants="$(cat /usr/share/kmodtool/kernel-variants)"
else
	error_out 2  "Could not find /usr/share/kmodtool/kernel-variants"	
fi

# general sanity checks
if [[ ! "${target}" ]]; then
		error_out 2 "please pass target arch with --target"
elif [[ ! "${kmodname}" ]]; then
		error_out 2 "please pass kmodname with --kmodname"
elif [[ ! "${kernels_known_variants}" ]] ; then
		error_out 2 "could not determine known variants"
elif ( [[ "${obsolete_name}" ]] && [[ ! "${obsolete_version}" ]] ) ||  ( [[ ! "${obsolete_name}" ]] && [[ "${obsolete_version}" ]] ) ; then
		error_out 2 "you need to provide both --obsolete-name and --obsolete-version"
fi

# go
if [[ "${for_kernels}" ]]; then
	# this is easy:
	print_customrpmtemplate "${for_kernels}"
elif [[ "${build_kernels}" == "akmod" ]]; then
	# do only a akmod package
	print_akmodtemplate
	print_akmodmeta
else
	# seems we are on out own to decide for which kernels to build

	# we need more sanity checks in this case
	if [[ ! "${repo}" ]]; then
		error_out 2 "please provide repo name with --repo"
	elif ! $(which buildsys-build-${repo}-kerneldevpkgs &> /dev/null) ; then
		error_out 2 "buildsys-build-${repo}-kerneldevpkgs not found"
	fi

	# call buildsys-build-${repo}-kerneldevpkgs to get the list of kernels
	cmdoptions="--target ${target}"

	# filterfile to filter list of kernels?	
	if [[ "${filterfile}" ]] ; then
		 cmdoptions="${cmdoptions} --filterfile ${filterfile}"
	fi

	kernel_versions_to_build_for="$(buildsys-build-${repo}-kerneldevpkgs --${build_kernels} ${cmdoptions})"
	returncode=$?
	if (( ${returncode} != 0 )); then
		error_out 2 "buildsys-build-${repo}-kerneldevpkgs failed: $(buildsys-build-${repo}-kerneldevpkgs --${build_kernels} ${cmdoptions})"
	fi

	if [[ "${build_kernels}" == "current" ]] && [[ ! "${noakmod}" ]]; then
		print_akmodtemplate
	fi

	print_rpmtemplate 
fi
